name: Workflow Artefact
on: push

jobs:
  testartifact:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123 > text.txt
      - uses: actions/upload-artifact@v3
        with:
          name: myfirstartifact
          path: ./text.txt
