name: Workflow Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
      - name: Init cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('./vite-project/package-lock.json') }}
          path: ./vite-project/.npm
      - name: Install dependencies
        working-directory: ./vite-project
        run: npm ci --cache .npm --prefer-offline
      - name: Build application
        working-directory: ./vite-project
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./vite-project/dis

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - run: |
          ls
          ls build
