name: Workflow concurrence
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: waitforme
    steps:
      - run: |
          echo Very long step
          sleep 100
          echo Done !
