name: Workflow matrice
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cloud: ovh
            endpoint: url1
          - cloud: aws
            endpoint: url2
        # os: [ubuntu-latest, windows-latest, macos-latest]
        # vers: [12, 13, 14]
    steps:
      - run: echo ${{ matrix.os }} ${{ matrix.vers }}
