name: Workflow matrice
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        vers: [12, 13, 14]
        exclude:
          - os: windows-latest
            vers: 12
        # include:
        #   - cloud: ovh
        #     endpoint: url1
        #     os: ubuntu-latest
        #   - cloud: aws
        #     endpoint: url2

    steps:
      - run: echo ${{ matrix.os }} ${{ matrix.vers }}
    #   - run: echo ${{ matrix.cloud }} ${{ matrix.endpoint }} ${{ matrix.os }}
