name: Workflow run, shel, working directory et defaults
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
        working-directory: ./vite-project
      # - run: |
      #     pwd
      #   shell: sh
      # - run: |
      #     pwd
      #   shell: pwsh
