name: Commandes Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 123
      - run: echo ::debug::je suis ici
      - run: echo 456
    
      # - run: |
      #     echo ::group::mon groupe
      #     echo 1
      #     echo 2
      #     echo 3
      #     echo 4
      #     echo ::endgroup::
          
      # - run: echo fruit=pomme >> $GITHUB_OUTPUT
      #   id: step1
      # - run: echo ::error file=unfichier.txt,line=1,endline=2,col=5::fruit is ${{ steps.step1.outputs.fruit }} should be poire
      #   if: steps.step1.outputs.fruit !='poire'
