name: Commandes Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ::notice::Un message info
          echo ::warning::Un warning
          echo ::error::Une erreur
        
