name: Commandes Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo fruit=pomme >> $GITHUB_OUTPUT
        id: step1
      - run: echo ::error file=unfichier.txt,line=1,endline=2,col=5::fruit is ${{ steps.step1.outputs.fruit }} should be poire
        if: steps.step1.outputs.fruit !='poire'
